### PR TITLE
Deferred improvements

### PR DESCRIPTION
**Pull request by mmstick**
Resolves some of the items from https://github.com/pop-os/upgrade/issues/279

- Make up/down keys increment spinboxes by 1 instead of 3
- Make hours/minutes roll over when incrementing or decrementing beyond their limits.
- Consider making system-updater run apt autoremove to keep clutter from building up on the system
- Make the Pop!_Shop not immediately recheck for updates after clicking a notification from system-updater

Some other fixes include

- Run nix-channel --update before upgrading nix-env packages
- Avoid blocking the user service when a notification is shown
- Improved error messages on service startup
- Perf optimization from spawning main future on tokio runtime

Note that the GTK crate changes can only be tested from running the GTK demo locally with `just run`. An update to the system-updater dependency in pop-upgrade will get the change applied there.

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
The "rolling over" isn't quite what I expected (I was thinking e.g. 1:59 rolling over to 2:00, not 1:00), but having it this way is still an improvement. (The current way might be closer to how digital clocks work.) Up/down arrow keys are working as expected now.

The autoremove functionality doesn't seem to be working. I saw this in the logs when it tried to run:

```
Apr 26 12:20:02 pop-os pop-system-updater[29967]: The following packages will be REMOVED:
Apr 26 12:20:02 pop-os pop-system-updater[29967]:   gir1.2-gnomebluetooth-1.0 ltrace
Apr 26 12:20:02 pop-os pop-system-updater[29967]: 0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
Apr 26 12:20:02 pop-os pop-system-updater[29967]: After this operation, 375 kB disk space will be freed.
Apr 26 12:20:02 pop-os pop-system-updater[29967]: Do you want to continue? [Y/n] Abort.
```

**Comment by jackpot51** [comment]
It probably needs --yes

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
Autoremove is now working. Notifications are displaying properly, but clicking them no longer opens the Pop!_Shop. I get this in the journal instead:
```
Apr 27 09:34:26 pop-os pop-system-updater[9273]: Backtrace omitted. Run with RUST_BACKTRACE=1 to display it.
Apr 27 09:34:26 pop-os pop-system-updater[9273]: Run with RUST_BACKTRACE=full to include source snippets.
Apr 27 09:34:26 pop-os pop-system-updater[9273]: The application panicked (crashed).
Apr 27 09:34:26 pop-os pop-system-updater[9273]:   there is no reactor running, must be called from the context of a Tokio 1.x runtime
Apr 27 09:34:26 pop-os pop-system-updater[9273]: in daemon/src/notify.rs, line 43
Apr 27 09:34:26 pop-os pop-system-updater[9273]: thread: <unnamed>
```

**Comment by mmstick** [comment]
I see. Quick fix

**Comment by jacobgkau** [comment]
Clicking the notification opens the Pop!_Shop now (still to the wrong page sometimes, not a regression.)

> Make the Pop!_Shop not immediately recheck for updates after clicking a notification from system-updater

I'm not seeing this one work-- PackageKit still runs a `refresh-cache` transaction after clicking the notification (I still see the spinner in the Pop!_Shop for a few seconds while that's happening, and if the process wasn't already running, I also see `Checking for Updates` on the Installed page.)

I see that we're not explicitly restarting the Pop!_Shop process anymore, but the Pop!_Shop seems to check for updates every time its GUI is opened even if it's already running. Should this be ignored for now? (I assume it would require modification to the Pop!_Shop and not just system-updater to achieve this.)

**Comment by mmstick** [comment]
That's unavoidable for as long as the shop uses packagekit. This one change only avoids restarting the appcenter process.

**Review by jacobgkau — APPROVED** [review]
> That's unavoidable for as long as the shop uses packagekit.

I don't see why this statement would be true, packagekit will only perform operations when the Pop!_Shop requests it, right?

All of the other improvements are working.

**Comment by mmstick** [comment]
It does request to refresh the cache when its opened, and it's required to do so since it doesn't use the same cache as apt.

**Pull request merged**
