### PR TITLE
Use pop-shop dbus service to show updates, and start it if it wasn't running

### PR DESCRIPTION
**Pull request by mmstick**
Requires https://github.com/pop-os/shop/pull/350 to be installed

The notification logic can be tested from source with `cargo run --example appcenter_updates`

### CODE REVIEW

**Comment by jacobgkau** [comment]
Doesn't seem to be working. I now get this in the log when I try to click the notification before the Pop!_Shop is running:

```
Apr 29 11:56:24 pop-os pop-system-updater[3133]:  INFO pop_system_updater::service::session: displaying notification of available updates
Apr 29 11:56:32 pop-os io.elementary.a[4963]: cannot open display: 
Apr 29 11:56:35 pop-os pop-system-updater[3133]: io.elementary.appcenter show-updates dbus method failed: MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.ServiceUnknown")))), Some("The name io.elementary.appcenter was not provided by any .service files"), Msg { type: Error, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), reply-serial: 3, body: Signature: [
Apr 29 11:56:35 pop-os pop-system-updater[3133]:         s (115),
Apr 29 11:56:35 pop-os pop-system-updater[3133]: ] })
```

**Comment by mmstick** [comment]
Maybe this is the reason? `io.elementary.a[4963]: cannot open display: `. Haven't been able to replicate that issue so far.

Steps I've done is:

- Add the `shop` and `show-updates` staging branches
- Installed `pop-shop pop-system-updater`
- Restarted
- `rm -rf ~/.cache/pop-system-updater`
- `kill $(pidof io.elementary.appcenter)`
- systemctl --user restart pop-system-updater-local

Then clicking the notification started the appcenter and then opened the installed page.

**Comment by jacobgkau** [comment]
> - `kill $(pidof io.elementary.appcenter)`

If I kill the shop process and make the notification show up, then it does work. I can only recreate this if I remove the cache, reboot, log in, and click the notification before the shop process has ever started that boot/login.

**Comment by jacobgkau** [comment]
0383950 did not change the behavior, the Pop!_Shop still fails to open up the first time the notification is clicked before the appcenter process has started after boot/login.

```
-- Boot 0222dc4a5f1c4027b81acfb94b9dbe77 --
Apr 29 15:02:16 pop-os pop-system-updater[1856]:  INFO pop_system_updater::config: loading config: "/home/system76/.config/pop-system-updater/config.ron"
Apr 29 15:02:16 pop-os pop-system-updater[1856]:  INFO pop_system_updater::config: loading config: "/home/system76/.cache/pop-system-updater/cache.ron"
Apr 29 15:02:16 pop-os pop-system-updater[1856]:  INFO pop_system_updater::config: writing config: "/home/system76/.cache/pop-system-updater/cache.ron"
Apr 29 15:02:16 pop-os systemd[1813]: Starting Local session service for the Pop System Updater...
Apr 29 15:02:16 pop-os systemd[1813]: Started Local session service for the Pop System Updater.
Apr 29 15:02:17 pop-os pop-system-updater[1856]:  INFO pop_system_updater::package_managers::apt: debian packages requiring updates: 9
Apr 29 15:02:17 pop-os pop-system-updater[1856]:  INFO pop_system_updater::service::session: displaying notification of available updates
Apr 29 15:02:23 pop-os io.elementary.a[4809]: cannot open display: 
Apr 29 15:02:26 pop-os pop-system-updater[1856]: io.elementary.appcenter show-updates dbus method failed: MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.ServiceUnknown")))), Some("The name io.elementary.appcenter was not provided by any .service files"), Msg { type: Error, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), reply-serial: 3, body: Signature: [
Apr 29 15:02:26 pop-os pop-system-updater[1856]:         s (115),
Apr 29 15:02:26 pop-os pop-system-updater[1856]: ] })
Apr 29 15:02:26 pop-os pop-system-updater[4854]: connecting to client to show updates
Apr 29 15:02:26 pop-os pop-system-updater[4854]: Failed to show updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.appcenter was not provided by any .service files
Apr 29 15:02:26 pop-os io.elementary.a[4854]: cannot open display: 
```

> `The name io.elementary.appcenter was not provided by any .service files`

There's no systemd service for the Pop!_Shop/appcenter, not sure if that has anything to do with it?

**Comment by mmstick** [comment]
The problem is still `io.elementary.a[4854]: cannot open display: ` but I'm not sure why it'd have that issue. It should be doing the same thing on the current version. Systemd user session services have the DISPLAY and XAUTHORITY environment variables set when they launch by systemd, so there shouldn't be any issue launching windows from it.

The error about not finding the service file is because it couldn't find the DBus service active, and that happens because the application is aborting on the `cannot open display` error.

**Comment by mmstick** [comment]
Would you happen to be on a Wayland session?

**Comment by mmstick** [comment]
`systemctl --user show-environment | grep DISPLAY` should return something like `DISPLAY:=0`

**Comment by jacobgkau** [comment]
> Would you happen to be on a Wayland session?

No, I'm using the default X11 session. Double-checked with `echo $XDG_SESSION_TYPE` just to make sure.

Still having the issue on db71692: [out.txt](https://github.com/pop-os/system-updater/files/8604797/out.txt)

```
May 02 10:52:22 pop-os pop-system-updater[2244]:  INFO pop_system_updater::service::session: displaying notification of available updates
May 02 10:52:29 pop-os io.elementary.a[4960]: cannot open display: 
May 02 10:52:32 pop-os pop-system-updater[2244]: io.elementary.appcenter show-updates dbus method failed: MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.ServiceUnknown")))), Some("The name io.elementary.appcenter was not provided by any .service files"), Msg { type: Error, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), reply-serial: 3, body: Signature: [
May 02 10:52:32 pop-os pop-system-updater[2244]:         s (115),
May 02 10:52:32 pop-os pop-system-updater[2244]: ] })
May 02 10:52:32 pop-os pop-system-updater[5005]: connecting to client to show updates
May 02 10:52:32 pop-os pop-system-updater[5005]: Failed to show updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.appcenter was not provided by any .service files
May 02 10:52:32 pop-os io.elementary.a[5005]: cannot open display: 
```

After this failure, if I wait until `io.elementary.appcenter -s` starts by itself, then clear the cache and restart system-updater --user, then clicking the notification does work.

**Comment by mmstick** [comment]
Then perhaps there's a race condition with getting the DISPLAY variable set.

**Comment by mmstick** [comment]
This change will wait 10s for first execution, then if DISPLAY is not set it'll wait 5s and restart the service.

**Review by jacobgkau — APPROVED** [review]
Working as expected after bf11972, and it's still working on c75306a. If I click the notification before the shop's running, it's started with `--silent` (it just uses the short-form `-s` when I wait for it to start itself.) The shop opens up to the correct page in either case.

I'm not seeing a noticeable delay anywhere, especially not a whole 10 seconds, so this solution doesn't seem to cause any problems.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
