### PR TITLE
fix: When checking for updates, send CheckForUpdate instead of Update

### LINKED ISSUE #3: Installing updates on every boot regardless of schedule or auto-update settings
Updates are running when they're scheduled to, but the global system-updater process is also installing updates at boot when it should not be, even when `Automatic Updates` is disabled. This is happening on 22.04 and 21.10.

### PR DESCRIPTION
**Pull request by jacobgkau**
Attempting to fix https://github.com/pop-os/system-updater/issues/3.

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
Built locally and this seems to be working, QA may want to confirm once it's built by the build server.

**Comment by mmstick** [comment]
Maybe it should conditionally use update when automatic updates are enabled.

**Comment by jackpot51** [comment]
Aren't the timers for automatic install of packages and automatic checking of package updates supposed to be different though?

**Comment by jacobgkau** [comment]
I think this was for the "update when available" functionality, that will need to be handled some other way.

**Comment by mmstick** [comment]
Yeah, this one is for update when available

**Comment by jacobgkau** [comment]
So if `auto_update` is `true` and `schedule` is `None`, then it should Update; otherwise, it should only CheckForUpdate.

**Comment by mmstick** [comment]
It could send a new event. `UpdateWhenAvailable` or something like that. Then the main loop processing those messages can decide if it should do anything based on the config.

Or the config having that setting enabled could spawn this loop and then abort the task if its later disabled.

If `config.auto_update` is `true` and `config.schedule` is `None`, update-when-available is set.

**Review by n3m0-22 — APPROVED** [review]

**Comment by jacobgkau** [comment]
Regardless of this breaking `Update when Available`, we'd like to move forward with the fix at least so people don't have updates running without their consent in the meantime. It looks like it's going to be a little more involved to check the config in this loop or otherwise handle `Update when Available`.

(Looking at https://github.com/pop-os/system-updater/blob/500a384cf687e5e14aba8e01caec0157dc63a167/daemon/src/service/system.rs#L298, I'm not sure we actually need to worry about this? It almost seems more like this was just a case of using the wrong event.)

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
