### PR TITLE
Completion of system-updater service + GTK3 widget

### PR DESCRIPTION
**Pull request by mmstick**
Merge with https://github.com/pop-os/shop/pull/342

### CODE REVIEW

**Comment by jacobgkau** [comment]
I'm not sure 07d5615 worked, I have that version installed and I still get the +/- buttons focused with tab.

https://user-images.githubusercontent.com/7199422/162490995-05db7bf0-2881-446d-ba86-aee7478ebe42.mp4

As shown in that screencast, it also looks like the dialog loads a 12 value as 00 instead of 12.

**Comment by mmstick** [comment]
Did you test with cargo run? Because the GTK widget here isn't dynamically loaded by pop-upgrade. It's statically linked when pop-upgrade is compiled.

**Comment by jacobgkau** [comment]
> Did you test with cargo run? Because the GTK widget here isn't dynamically loaded by pop-upgrade. It's statically linked when pop-upgrade is compiled.

When I try to `cargo run` from the `system-updater` repo/directory, I get this:

```
     Running `target/debug/pop-system-updater`
 INFO pop_system_updater::config: loading config: "/home/system76/.config/pop-system-updater/config.ron"
Backtrace (most recent call first):
  File "rust:library/core/src/result.rs", line 1022, in core::result::Result<T,E>::expect
  File "/home/system76/system-updater/src/service/session.rs", line 46, in pop_system_updater::service::session::run::{{closure}}
    connection
  File "rust:library/core/src/future/mod.rs", line 84, in <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  File "/home/system76/system-updater/src/main.rs", line 36, in pop_system_updater::main::{{closure}}
    let _ = dbg!(crate::service::session::run().await);
  File "rust:library/core/src/future/mod.rs", line 84, in <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  File "/home/system76/.cargo/registry/src/github.com-1ecc6299db9ec823/async-io-1.6.0/src/driver.rs", line 142, in async_io::driver::block_on
    if let Poll::Ready(t) = future.as_mut().poll(cx) {
  File "/home/system76/system-updater/src/main.rs", line 30, in pop_system_updater::main
    smol::block_on(async move {

The application panicked (crashed).
  failed to request session name: NameTaken
in src/service/session.rs, line 49
thread: main
```

I tried stopping `com.system76.Scheduler.service` and `com.system76.SystemUpdater.service`, but got the same thing. What else should I be doing? I also tried doing `cargo run` from the `pop-upgrade` repo/directory, but got ``error: failed to select a version for the requirement `apt-cmd = "*"` ``.

If pop-upgrade b377568 was supposed to include system-updater b8f764b, I'm still seeing tab select the -/+ buttons in between the text boxes. 12 no longer loads as 00, but now loads as 01, which is actually inaccurate. (Opening the dialog when it's been saved at 12 doesn't actually change the saved value to 01 unless I modify the number in the spinbox.)

https://user-images.githubusercontent.com/7199422/162519189-fc79eb24-6ade-4bf6-985c-a69c45f2d36c.mp4

**Comment by jacobgkau** [comment]
Sorry, I found your comment from https://github.com/pop-os/upgrade/pull/225 that `cargo run` has to be run from the `gtk` directory. That works, still seeing what I described above.

**Comment by mmstick** [comment]
Tab still isn't being observed correctly?

**Comment by jacobgkau** [comment]
> Tab still isn't being observed correctly?

Oh, trying again, it looks like I didn't have the branch checked out. Tab is working correctly on b8f764b via `cargo run`, although 12 loading as 01 as shown in the video is still happening.

It looks like pop-upgrade b377568 does not include the latest system-updater.

**Comment by mmstick** [comment]
Yeah I'll need to fix the hour values being read from a config not counting from 1

**Comment by jacobgkau** [comment]
On a1eb0f6, 12's are sometimes loading as 11's and sometimes loading as 01's.

https://user-images.githubusercontent.com/7199422/162792617-9d313b41-abd5-4bed-8289-bc8aac50288c.mp4

I also noticed that if I type "1" twice in the hour box (with a 1 already populated to start with), I end up with a 12 for some reason. This clip is only pressing the "1" key:

https://user-images.githubusercontent.com/7199422/162792621-357333fe-27aa-4301-9632-91efc4faad36.mp4

**Comment by mmstick** [comment]
The 12 happens because the text entry changed to 111, but 12 is the maximum value permitted.

**Comment by jacobgkau** [comment]
> The 12 happens because the text entry changed to 111, but 12 is the maximum value permitted.

That makes sense. Can we limit the text box to 2 characters maximum so that doesn't happen?

Another issue happening now, it seems there's a 1-hour offset between the time saved/shown in the GUI and the time that's saved. I set the GUI to install updates Monday at 4:15 PM (which is 16:15 in 24-hour time), and the logs showed `interval: Monday, hour: 15, minute: 15`, an hour earlier; updates did not run at 4:15 PM like I tried to configure. I then set the updates to run at 5:18 and they ran at 4:18.

**Comment by mmstick** [comment]
Looking into it

**Comment by mmstick** [comment]
I'll need a bit more time for this. The crate that I was using for scheduling the updates turned out to be unmaintained and crashes if a 23rd hour is specified. Some other crates I tried are also poorly designed for this purpose. I've just about finished a better alternative we can use here.

**Comment by mmstick** [comment]
New Rust crate complete (`pop-task-scheduler`, name pending changes) and [included in this PR](https://github.com/pop-os/system-updater/tree/system-updater/scheduler) as a package in this repository's workspace. I've tested and validated that it works right down to the exact second that the minute changes to match the configuration file.

**Comment by jacobgkau** [comment]
On 2b8f2ae, I am still seeing the time saved in the config file be an hour earlier than what's configured in the GUI as described [earlier](https://github.com/pop-os/system-updater/pull/1#issuecomment-1095642508) (thank you @n3m0-22 for bringing this back up.)

**Comment by mmstick** [comment]
As in seeing a value of `0` for the 1st hour?

**Comment by jacobgkau** [comment]
> As in seeing a value of `0` for the 1st hour?

If I set it to 4:00 PM, it saves as 15:00, which would normally be 3:00 PM in 24-hour time. 12 AM saves as 11:00 (which seems off in a different way), and 1 AM saves as 00:00.

I'm trying to confirm whether it's actually running updates at the wrong time or not, but having to wait a minute between each attempt. Is the time format for the config file different from standard 24-hour time?

**Comment by mmstick** [comment]
At least the config file stores the value as an integer from `0-23` with 23 being `24:00` to a human

**Comment by jacobgkau** [comment]
> At least the config file stores the value as an integer from `0-23` with 23 being `24:00` to a human

That's poor human readability for the config file, but understood. That means 12 PM should save as 11 and 12 AM should save as 0, not 11, right? (That's not what I'm seeing; I'm seeing 12 AM save as 11 and 12 PM run updates immediately while refusing to save at all.)

**Comment by mmstick** [comment]
I'll check it out

**Comment by mmstick** [comment]
Okay. That should be fixed now.

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
On 4a20245, hours and minutes are not saving at all (I've tried typing, using the spinbox buttons, and exiting the dialogue.)

**Comment by mmstick** [comment]
Was the service upgraded/restarted?

**Comment by jacobgkau** [comment]
> Was the service upgraded/restarted?

Yes, I rebooted after installing the updates. Here is a video showing the config file not being updated, logs not showing any saving, and dialogue loading the config file's values every time I open it:

https://user-images.githubusercontent.com/7199422/163908406-a1194a35-4770-4d43-ab31-178e710e25b6.mp4

**Comment by jacobgkau** [comment]
Wait, I rebooted a second time and now it's saving. Not sure what was happening, but maybe a false flag.

**Comment by mmstick** [comment]
It is working here:

```
INFO pop_system_updater::service::system: received event: SetSchedule(Some(Schedule { interval: Weekdays, hour: 4, minute: 31 }))
 INFO pop_system_updater::service::system: Changing scheduling to Some(Schedule { interval: Weekdays, hour: 4, minute: 31 })
 INFO pop_system_updater::service::system: scheduling for Schedule { interval: Weekdays, hour: 4, minute: 31 }
 INFO pop_system_updater::config: writing config: "/etc/pop-system-updater/config.ron"
 INFO pop_system_updater::service::system: system configuration file updated
 INFO pop_system_updater::service::system: UPDATE TRIGGERED
 INFO pop_system_updater::service::system: received event: Update
 INFO pop_system_updater::service::system: checking for system updates
 INFO pop_system_updater::package_managers::apt: updating package lists
```

**Comment by jacobgkau** [comment]
Alright, saving/loading does appear to be working now.

I'm still not seeing updates actually get installed at the time I configured, still looking into that. I am seeing `pop-upgrade.service` check for a release upgrade (which performs an `apt update` first, presumably to self-update itself if necessary) every minute, which seems pretty often. Is that expected?

**Comment by jacobgkau** [comment]
Alright, saving/loading does seem to be working now. I'm still not seeing updates get installed at the correct time-- at 8:48, I set it to Monday at 8:49 PM, and `apt upgrade` still has updates that it offers to install when I run it manually at 8:50.

I do see `pop-upgrade.service` checking for a release upgrade (which also performs an `apt update` first, presumably to self-update itself if necessary) every minute, which seems pretty often. Is that expected?

**Comment by mmstick** [comment]
No, but I think I know why.

**Comment by mmstick** [comment]
Needs one remaining fix from the GTK side

**Comment by jacobgkau** [comment]
Saving/loading is working more reliably now. I'm still not seeing updates actually being installed at the selected date/time-- monitoring `pop-upgrade.service`, `com.system76.SystemUpdater.service`, and `--user com.system76.SystemUpdater.Local.service`, none of them have any output when the clock turns to the minute I configured (and waiting for it to turn to the next minute.)

Also, kind of a UX question, but if I choose `Update when Available` (which greys out the date/time picker), how often can I expect the system to actually check for updates in that case? I did see an update get installed a couple of minutes after enabling that option, but it wasn't immediate; I assume it must still have some interval for checking? (I know the Pop!_Shop was able to detect when the user makes a change to the repos, but there's no push mechanism from the apt servers to clients that I'm aware of.)

I did notice the `Update when Available` on/off switch always loads as off, even when the feature is on:

https://user-images.githubusercontent.com/7199422/163937945-bd87b7b5-ef8b-494b-894f-4f2b8c8d3b6e.mp4

The feature being on also causes the time/date to load as Monday at 1 AM, instead of whatever was previously configured, although that one can be deferred if necessary.

**Comment by mmstick** [comment]
Did you see an event like this from the `SystemUpdater.service` when setting the time manually? It just worked for me when I set the time for 1:29 PM.

```
scheduling for Schedule { interval: Weekdays, hour: 13, minute: 29 }
```

I currently have the update-when-available setting set to do its first update 1 minute after it has been turned on. Turning it off before the 1 minute has elapsed will cancel it. Then it does an update every 12 hours.

I see what you mean by it always loading in an off state.

**Comment by mmstick** [comment]
If it would help I can also make a change to log the precise number of seconds the scheduler is counting down to the next update.

**Comment by mmstick** [comment]
Now when changing the time you should see

```
 INFO pop_system_updater::service::system: scheduling for Schedule { interval: Weekdays, hour: 14, minute: 5 }
 INFO async_cron_scheduler::scheduler: next job in 48 seconds
```

**Comment by jacobgkau** [comment]
> Now when changing the time you should see

That might be helpful. I changed the time to Tuesday at 8:59 AM at 8:58 AM and saw this:

```
Apr 19 08:58:55 pop-os pop-system-updater[1828]:  INFO pop_system_updater::service::system: scheduling for Schedule { interval: Tuesday, hour: 8, minute: 59 }
Apr 19 08:58:55 pop-os pop-system-updater[1828]:  INFO async_cron_scheduler::scheduler: next job in 518404 seconds
```

That should have been less than 60 seconds, but instead it was almost exactly 6 days (not 7). I tried changing it to a few other days, and it ran immediately when I set it to Sunday. Is it possible there's some kind of day offset occurring? Thursday says `next job in 86205 seconds` and Wednesday says `next job in 604593 seconds`, which doesn't make sense because Wednesday is closer to now than Thursday, so its number should be lower.

**Comment by jacobgkau** [comment]
After fiddling some more, Wednesday at 9:17 shows less than 60 seconds until the next job, so I think the scheduler thinks tomorrow is today (unless I'm losing my mind and today, 19 April 2022, isn't actually a Tuesday).

I think that explains the Wednesday/Thursday discrepancy, because the time at that point would have "passed" if it was Wednesday, making Thursday the next scheduled update.

Setting to Sunday still runs immediately, not sure why that is.

**Comment by mmstick** [comment]
The cron values for those dates are likely wrong. Checking

**Comment by mmstick** [comment]
It seems to be a potential bug in the cron crate, but using the shorthand name of the date (`TUE`) works fine. Pushing change in a moment.

**Comment by mmstick** [comment]
This change only affects the system service, so the GTK widget in pop-upgrade functions the same.

**Comment by jacobgkau** [comment]
After installing the last update and rebooting, I had another case like I did [earlier](https://github.com/pop-os/system-updater/pull/1#issuecomment-1101931677) where the `com.system76.SystemUpdater` service wasn't found, so saving times wasn't working. I saw this again in `systemctl status com.system76.SystemUpdater`:

```
○ com.system76.SystemUpdater.service - Distribution updater
     Loaded: loaded (/lib/systemd/system/com.system76.SystemUpdater.service; enabled; vendor preset: enabled)
     Active: inactive (dead)

Apr 19 10:05:45 pop-os systemd[1]: com.system76.SystemUpdater.service: Found ordering cycle on network-online.target/start
Apr 19 10:05:45 pop-os systemd[1]: com.system76.SystemUpdater.service: Found dependency on network.target/start
Apr 19 10:05:45 pop-os systemd[1]: com.system76.SystemUpdater.service: Found dependency on com.system76.SystemUpdater.service/start
Apr 19 10:05:45 pop-os systemd[1]: com.system76.SystemUpdater.service: Job network-online.target/start deleted to break ordering cycle starting with com.system76.SystemUpdater.service/start
```

I've rebooted a second time now and am still seeing the same issue. I'll keep trying, but could this indicate some kind of race condition or other situation where the service is failing to load?

Update: it did work after a third reboot (the unreliability is obviously concerning.)

**Comment by mmstick** [comment]
That's new. Looking into it.

**Comment by jacobgkau** [comment]
I am seeing scheduling work reliably and updates install on schedule as expected now, including specific days of the week and the "Weekdays" option. Still need to circle back and check notification behavior again.

**Comment by mmstick** [comment]
That commit only makes changes to the systemd service files.

**Comment by jacobgkau** [comment]
791acef did not fix the startup issue, I see the same failure after installing that update and rebooting.

```
system76@pop-os:~$ apt policy pop-system-updater 
pop-system-updater:
  Installed: 0.1.0~1650385857~22.04~791acef
  Candidate: 0.1.0~1650385857~22.04~791acef
  Version table:
 *** 0.1.0~1650385857~22.04~791acef 1002
       1002 http://apt.pop-os.org/staging/system-updater jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     0.1.0~1649205922~22.04~44748b7 1002
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1002 http://apt.pop-os.org/staging/master jammy/main amd64 Packages
system76@pop-os:~$ systemctl status com.system76.SystemUpdater.service 
○ com.system76.SystemUpdater.service - Distribution updater
     Loaded: loaded (/lib/systemd/system/com.system76.SystemUpdater.service; enabled; vendor preset: enabled)
     Active: inactive (dead)

Apr 19 11:21:41 pop-os systemd[1]: network-online.target: Found ordering cycle on network.target/start
Apr 19 11:21:41 pop-os systemd[1]: network-online.target: Found dependency on com.system76.SystemUpdater.service/start
Apr 19 11:21:41 pop-os systemd[1]: network-online.target: Found dependency on network-online.target/start
Apr 19 11:21:41 pop-os systemd[1]: network-online.target: Job network.target/start deleted to break ordering cycle starting with network-online.target/start
system76@pop-os:~$ cat /usr/lib/systemd/system/com.system76.SystemUpdater.service 
[Unit]
After=network-online.target
Description=Distribution updater

[Service]
Type=dbus
BusName=com.system76.SystemUpdater
ExecStart=/usr/bin/pop-system-updater
Restart=on-failure
KillMode=process
SendSIGKILL=no

[Install]
WantedBy=default.target
Alias=pop-system-updater.servicesystem76@pop-os:~$ 
```

**Comment by mmstick** [comment]
If you remove the `WantedBy=` parts (or change it to `WantedBy=multi-user.target`), does it fix it?

**Comment by jacobgkau** [comment]
> If you remove the `WantedBy=` parts (or change it to `WantedBy=multi-user.target`), does it fix it?

Changing to `multi-user.target` for the global service did not fix it for the global service, nor did removing the `WantedBy` line from that service entirely.

It looks like the local service actually isn't failing to start (at least, I'm seeing it work when the global service has failed.) The global service is what handles saving the time after it's been changed, so that's still not working when this occurs.

**Comment by mmstick** [comment]
I did two restarts with the latest changes that I just pushed and hadn't seen any systemd service conflicts. Maybe that fixed it.

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
I still had the issue the first reboot after installing bf18d3c.

**Comment by mmstick** [comment]
Do you have the full logs from systemd on that cyclic issue? All I could find searching this error was a mention of a fstab mount with `network-online` as a requires.

**Comment by mmstick** [comment]
Were there any errors printed in the journald logs besides that?

**Comment by jacobgkau** [comment]
Not that I can see: [out.txt](https://github.com/pop-os/system-updater/files/8515545/out.txt)

```
Apr 19 12:09:16 pop-os systemd[1]: Hostname set to <pop-os>.
Apr 19 12:09:16 pop-os systemd[1]: network.target: Found ordering cycle on com.system76.SystemUpdater.service/start
Apr 19 12:09:16 pop-os systemd[1]: network.target: Found dependency on network-online.target/start
Apr 19 12:09:16 pop-os systemd[1]: network.target: Found dependency on network.target/start
Apr 19 12:09:16 pop-os systemd[1]: network.target: Job com.system76.SystemUpdater.service/start deleted to break ordering cycle starting with network.target/start
Apr 19 12:09:16 pop-os systemd[1]: Queued start job for default target Graphical Interface.
```

```
Apr 19 12:09:16 pop-os apport[906]:  * Starting automatic crash report generation: apport
Apr 19 12:09:16 pop-os systemd[1]: com.system76.SystemUpdater.service: Found ordering cycle on network-online.target/start
Apr 19 12:09:16 pop-os kernel: usbcore: registered new interface driver uvcvideo
Apr 19 12:09:16 pop-os kernel: [drm] [nvidia-drm] [GPU ID 0x00000100] Loading driver
Apr 19 12:09:16 pop-os systemd[1]: com.system76.SystemUpdater.service: Found dependency on network.target/start
Apr 19 12:09:16 pop-os systemd[1]: com.system76.SystemUpdater.service: Found dependency on com.system76.SystemUpdater.service/start
Apr 19 12:09:16 pop-os systemd[1]: com.system76.SystemUpdater.service: Job network-online.target/start deleted to break ordering cycle starting with com.system76.SystemUpdater.service/start
Apr 19 12:09:16 pop-os NetworkManager[917]: <info>  [1650391756.5435] NetworkManager (version 1.36.4) is starting... (for the first time)
```

Those are the only occurrences of `SystemUpdater` in the log.

**Comment by mmstick** [comment]
`systemd-analyze verify network-online.target` this seems to give me the info I need.

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
32b8640 seems to have fixed the startup issue.

Updates install at the configured time.

Notification are dispalying as expected. If I click a notification, it does not go away; if I close the Pop!_Shop and then click it again, it doesn't open the Pop!_Shop again.

https://user-images.githubusercontent.com/7199422/164085687-8a31e379-1a33-4143-af9f-e79abefb952d.mp4

I understand we're deferring the Pop!_Shop not opening to the correct tab if it was already running, but can we either dismiss the notification when it's clicked (preferred, and seems like it would be easier) or fix this so it opens the Pop!_Shop back up when it's clicked again?

**Comment by mmstick** [comment]
It should be getting dismissed on first click

**Review by jackpot51 — DISMISSED** [review]

**Review by jackpot51 — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
Notification behavior is working as expected now; the notification goes away after clicking. Upgrades are still running at the scheduled time. All the basics are in working order.

**Pull request merged**
